CREATE TABLE RESPOSTAS(
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DESCRICAO VARCHAR(120)
);
CREATE TABLE MENSAGENS(
    ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DESCRICAO VARCHAR(120),
    ID_RESPOSTA INT NOT NULL
);

SELECT * FROM RESPOSTAS RSP INNER JOIN MENSAGENS MSG ON MSG.ID_RESPOSTA = RSP.ID WHERE 
ALTER TABLE MENSAGENS ADD CONSTRAINT FK_RESPOSTA FOREIGN KEY (ID_RESPOSTA) REFERENCES RESPOSTAS(ID);